name: CI

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize]
  #schedule:
  #- cron: "0 0 */1 * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
    - name: install linting packages
      run: |
        npm install -g \
          awesome-lint \
          remark-cli \
          remark-lint \
          remark-lint-no-dead-urls
    - name: scan for dead urls
      run: |
        npx remark \
          -u remark-lint-no-dead-urls \
          ./README.md
    - name: run awesome-lint
      run: npx awesome-lint ./README.md
